# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zzp/keystone/elasticlave

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zzp/keystone/elasticlave

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zzp/keystone/elasticlave/CMakeFiles /home/zzp/keystone/elasticlave/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zzp/keystone/elasticlave/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run-tests

# Build rule for target.
run-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-tests
.PHONY : run-tests

# fast build rule for target.
run-tests/fast:
	$(MAKE) -f CMakeFiles/run-tests.dir/build.make CMakeFiles/run-tests.dir/build
.PHONY : run-tests/fast

#=============================================================================
# Target rules for targets named qemu

# Build rule for target.
qemu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qemu
.PHONY : qemu

# fast build rule for target.
qemu/fast:
	$(MAKE) -f CMakeFiles/qemu.dir/build.make CMakeFiles/qemu.dir/build
.PHONY : qemu/fast

#=============================================================================
# Target rules for targets named qemu-pmp-bug.patch

# Build rule for target.
qemu-pmp-bug.patch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qemu-pmp-bug.patch
.PHONY : qemu-pmp-bug.patch

# fast build rule for target.
qemu-pmp-bug.patch/fast:
	$(MAKE) -f CMakeFiles/qemu-pmp-bug.patch.dir/build.make CMakeFiles/qemu-pmp-bug.patch.dir/build
.PHONY : qemu-pmp-bug.patch/fast

#=============================================================================
# Target rules for targets named qemu-secure-boot.patch

# Build rule for target.
qemu-secure-boot.patch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qemu-secure-boot.patch
.PHONY : qemu-secure-boot.patch

# fast build rule for target.
qemu-secure-boot.patch/fast:
	$(MAKE) -f CMakeFiles/qemu-secure-boot.patch.dir/build.make CMakeFiles/qemu-secure-boot.patch.dir/build
.PHONY : qemu-secure-boot.patch/fast

#=============================================================================
# Target rules for targets named buildroot

# Build rule for target.
buildroot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 buildroot
.PHONY : buildroot

# fast build rule for target.
buildroot/fast:
	$(MAKE) -f CMakeFiles/buildroot.dir/build.make CMakeFiles/buildroot.dir/build
.PHONY : buildroot/fast

#=============================================================================
# Target rules for targets named sm

# Build rule for target.
sm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sm
.PHONY : sm

# fast build rule for target.
sm/fast:
	$(MAKE) -f CMakeFiles/sm.dir/build.make CMakeFiles/sm.dir/build
.PHONY : sm/fast

#=============================================================================
# Target rules for targets named linux

# Build rule for target.
linux: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linux
.PHONY : linux

# fast build rule for target.
linux/fast:
	$(MAKE) -f CMakeFiles/linux.dir/build.make CMakeFiles/linux.dir/build
.PHONY : linux/fast

#=============================================================================
# Target rules for targets named image

# Build rule for target.
image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 image
.PHONY : image

# fast build rule for target.
image/fast:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/build
.PHONY : image/fast

#=============================================================================
# Target rules for targets named bootrom

# Build rule for target.
bootrom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bootrom
.PHONY : bootrom

# fast build rule for target.
bootrom/fast:
	$(MAKE) -f CMakeFiles/bootrom.dir/build.make CMakeFiles/bootrom.dir/build
.PHONY : bootrom/fast

#=============================================================================
# Target rules for targets named linux64.patch

# Build rule for target.
linux64.patch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linux64.patch
.PHONY : linux64.patch

# fast build rule for target.
linux64.patch/fast:
	$(MAKE) -f CMakeFiles/linux64.patch.dir/build.make CMakeFiles/linux64.patch.dir/build
.PHONY : linux64.patch/fast

#=============================================================================
# Target rules for targets named driver-sync

# Build rule for target.
driver-sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 driver-sync
.PHONY : driver-sync

# fast build rule for target.
driver-sync/fast:
	$(MAKE) -f CMakeFiles/driver-sync.dir/build.make CMakeFiles/driver-sync.dir/build
.PHONY : driver-sync/fast

#=============================================================================
# Target rules for targets named driver

# Build rule for target.
driver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 driver
.PHONY : driver

# fast build rule for target.
driver/fast:
	$(MAKE) -f CMakeFiles/driver.dir/build.make CMakeFiles/driver.dir/build
.PHONY : driver/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named tools

# Build rule for target.
tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tools
.PHONY : tools

# fast build rule for target.
tools/fast:
	$(MAKE) -f CMakeFiles/tools.dir/build.make CMakeFiles/tools.dir/build
.PHONY : tools/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... run-tests"
	@echo "... qemu"
	@echo "... qemu-pmp-bug.patch"
	@echo "... qemu-secure-boot.patch"
	@echo "... buildroot"
	@echo "... sm"
	@echo "... linux"
	@echo "... image"
	@echo "... bootrom"
	@echo "... linux64.patch"
	@echo "... driver-sync"
	@echo "... driver"
	@echo "... tests"
	@echo "... tools"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

